# Generated by Django 4.2.16 on 2024-09-20 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conges_payes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jour_maladie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jour_ferie_dimanche', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prime_intensite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('divers_remuneration', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('indemnites_logement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('indemnites_transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotisation_syndicale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('autres_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_brut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_a_payer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_enfants', models.IntegerField(default=0)),
                ('taux_allocation_familiale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocation_familiale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to=settings.AUTH_USER_MODEL)),
                ('gestionnaire_paie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_etablies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heure_arrivee', models.TimeField()),
                ('heure_depart', models.TimeField()),
                ('heures_travail', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fiche_paie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.fichepaie')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HeureSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_heures', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fiche_paie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.fichepaie')),
            ],
            options={
                'verbose_name': 'Heure Supplémentaire',
                'verbose_name_plural': 'Heures Supplémentaires',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('type_credit', models.CharField(choices=[('avance', 'Avance sur salaire'), ('bonus', 'Bonus'), ('prime', 'Prime'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
