# Generated by Django 4.2.16 on 2024-09-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichepaie',
            name='mois',
        ),
    ]
