# Generated by Django 4.2.16 on 2024-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_remove_fichepaie_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichepaie',
            name='salaire_base_retenu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
