# Generated by Django 4.2.16 on 2024-09-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_fichepaie_salaire_base_retenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('P', 'Présent'), ('A', 'Absent')], default='A', max_length=1),
        ),
    ]
