# Generated by Django 4.2.16 on 2024-09-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_presence_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
