# Generated by Django 4.2.16 on 2024-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_alter_presence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='heuresupplementaire',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
